---
- name: Installation de Docker CE
  hosts: all
  gather_facts: No
  vars:
    - username: vagrant
  user: "{{username}}"
  become: yes

  tasks:
    - name: Install aptitude using apt (update apt list)
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
  
    - name: Installation de prérequises yum utils, device-mapper-persistent-data, lvm2
      apt: name={{ item }} state=present update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'python-pip', 'virtualenv', 'python3-setuptools']
            
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
      
    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker


    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Add user {{ username }} to docker group
      user:
        name: "{{ username }}"
        groups: docker
        append: yes
      become: yes
    
    - name: Install Docker Compose
      pip:
        name: docker-compose